language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

# install dependencies
install:
    - pip install .[dev] -r requirements.txt
    - pip install pytest pytest-cov
    - pip install coveralls

# run tests
script:
    - py.test

after_success:
    - coveralls