language: python
cache: pip
sudo: false

matrix:
  include:
   - env: TOXENV=py33
     python: 3.3
   - env: TOXENV=py34
     python: 3.4
   - env: TOXENV=py35
     python: 3.5

# Package installation
install:
  - pip install tox coveralls

# Run tests
script:
  tox

after_success:
  coveralls
