[tox]
envlist = py35,py36,py37

[testenv]
deps =
    pytest
    psutil
    manuel
    coverage
    pytest-cov

[tool.pytest]
env =
    PYTHONPATH=src/:$PYTHONPATH
norecursedirs =
          .tox
testpaths =
          tests/
adopts = --maxfail=2


[testenv:py35]
commands =
    pytest --doctest tests/


